_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.10
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
action_space:
    value: 128
actor_lr:
    value: 0.0003
agent:
    value: dqn
critic_lr:
    value: 0.001
dqn_lr:
    value: 0.001
env:
    value: sim
epsilon:
    value: 1
epsilon_decay:
    value: 0.99
epsilon_min:
    value: 0.01
gamma:
    value: 0.99
last_n:
    value: 10
max_step:
    value: 50
num_episodes:
    value: 500
seed:
    value: 42
state_space:
    value: 50
